# Generated by cpp11: do not edit by hand

cpp_mq_create_only <- function(name, max_num_msg, max_msg_size) {
  invisible(.Call(`_interprocess_cpp_mq_create_only`, name, max_num_msg, max_msg_size))
}

cpp_mq_open_only <- function(name) {
  invisible(.Call(`_interprocess_cpp_mq_open_only`, name))
}

cpp_mq_open_create <- function(name, max_num_msg, max_msg_size) {
  invisible(.Call(`_interprocess_cpp_mq_open_create`, name, max_num_msg, max_msg_size))
}

cpp_mq_send <- function(name, msg, priority) {
  .Call(`_interprocess_cpp_mq_send`, name, msg, priority)
}

cpp_mq_try_send <- function(name, msg, priority) {
  .Call(`_interprocess_cpp_mq_try_send`, name, msg, priority)
}

cpp_mq_timed_send <- function(name, msg, priority, timeout_ms) {
  .Call(`_interprocess_cpp_mq_timed_send`, name, msg, priority, timeout_ms)
}

cpp_mq_receive <- function(name) {
  .Call(`_interprocess_cpp_mq_receive`, name)
}

cpp_mq_try_receive <- function(name) {
  .Call(`_interprocess_cpp_mq_try_receive`, name)
}

cpp_mq_timed_receive <- function(name, timeout_ms) {
  .Call(`_interprocess_cpp_mq_timed_receive`, name, timeout_ms)
}

cpp_mq_get_max_msg <- function(name) {
  .Call(`_interprocess_cpp_mq_get_max_msg`, name)
}

cpp_mq_get_max_msg_size <- function(name) {
  .Call(`_interprocess_cpp_mq_get_max_msg_size`, name)
}

cpp_mq_get_num_msg <- function(name) {
  .Call(`_interprocess_cpp_mq_get_num_msg`, name)
}

cpp_mq_remove <- function(name) {
  .Call(`_interprocess_cpp_mq_remove`, name)
}

cpp_mutex_create_only <- function(name) {
  invisible(.Call(`_interprocess_cpp_mutex_create_only`, name))
}

cpp_mutex_open_only <- function(name) {
  invisible(.Call(`_interprocess_cpp_mutex_open_only`, name))
}

cpp_mutex_open_create <- function(name) {
  invisible(.Call(`_interprocess_cpp_mutex_open_create`, name))
}

cpp_mutex_remove <- function(name) {
  .Call(`_interprocess_cpp_mutex_remove`, name)
}

cpp_mutex_lock <- function(name) {
  .Call(`_interprocess_cpp_mutex_lock`, name)
}

cpp_mutex_try_lock <- function(name) {
  .Call(`_interprocess_cpp_mutex_try_lock`, name)
}

cpp_mutex_timed_lock <- function(name, timeout_ms) {
  .Call(`_interprocess_cpp_mutex_timed_lock`, name, timeout_ms)
}

cpp_mutex_unlock <- function(name) {
  .Call(`_interprocess_cpp_mutex_unlock`, name)
}

cpp_mutex_lock_sharable <- function(name) {
  .Call(`_interprocess_cpp_mutex_lock_sharable`, name)
}

cpp_mutex_try_lock_sharable <- function(name) {
  .Call(`_interprocess_cpp_mutex_try_lock_sharable`, name)
}

cpp_mutex_timed_lock_sharable <- function(name, timeout_ms) {
  .Call(`_interprocess_cpp_mutex_timed_lock_sharable`, name, timeout_ms)
}

cpp_mutex_unlock_sharable <- function(name) {
  .Call(`_interprocess_cpp_mutex_unlock_sharable`, name)
}

cpp_sem_create_only <- function(name, initial_count) {
  invisible(.Call(`_interprocess_cpp_sem_create_only`, name, initial_count))
}

cpp_sem_open_only <- function(name) {
  invisible(.Call(`_interprocess_cpp_sem_open_only`, name))
}

cpp_sem_open_create <- function(name, initial_count) {
  invisible(.Call(`_interprocess_cpp_sem_open_create`, name, initial_count))
}

cpp_sem_remove <- function(name) {
  .Call(`_interprocess_cpp_sem_remove`, name)
}

cpp_sem_post <- function(name) {
  .Call(`_interprocess_cpp_sem_post`, name)
}

cpp_sem_wait <- function(name) {
  .Call(`_interprocess_cpp_sem_wait`, name)
}

cpp_sem_try_wait <- function(name) {
  .Call(`_interprocess_cpp_sem_try_wait`, name)
}

cpp_sem_timed_wait <- function(name, timeout_ms) {
  .Call(`_interprocess_cpp_sem_timed_wait`, name, timeout_ms)
}

cpp_base62 <- function(value, hundredth, bytes) {
  .Call(`_interprocess_cpp_base62`, value, hundredth, bytes)
}

cpp_hash <- function(str) {
  .Call(`_interprocess_cpp_hash`, str)
}
