# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_mq_create_only <- function(name, max_num_msg, max_msg_size) {
    invisible(.Call(`_interprocess_rcpp_mq_create_only`, name, max_num_msg, max_msg_size))
}

rcpp_mq_open_only <- function(name) {
    invisible(.Call(`_interprocess_rcpp_mq_open_only`, name))
}

rcpp_mq_open_create <- function(name, max_num_msg, max_msg_size) {
    invisible(.Call(`_interprocess_rcpp_mq_open_create`, name, max_num_msg, max_msg_size))
}

rcpp_mq_send <- function(name, msg, priority) {
    .Call(`_interprocess_rcpp_mq_send`, name, msg, priority)
}

rcpp_mq_try_send <- function(name, msg, priority) {
    .Call(`_interprocess_rcpp_mq_try_send`, name, msg, priority)
}

rcpp_mq_timed_send <- function(name, msg, priority, timeout_ms) {
    .Call(`_interprocess_rcpp_mq_timed_send`, name, msg, priority, timeout_ms)
}

rcpp_mq_receive <- function(name) {
    .Call(`_interprocess_rcpp_mq_receive`, name)
}

rcpp_mq_try_receive <- function(name) {
    .Call(`_interprocess_rcpp_mq_try_receive`, name)
}

rcpp_mq_timed_receive <- function(name, timeout_ms) {
    .Call(`_interprocess_rcpp_mq_timed_receive`, name, timeout_ms)
}

rcpp_mq_get_max_msg <- function(name) {
    .Call(`_interprocess_rcpp_mq_get_max_msg`, name)
}

rcpp_mq_get_max_msg_size <- function(name) {
    .Call(`_interprocess_rcpp_mq_get_max_msg_size`, name)
}

rcpp_mq_get_num_msg <- function(name) {
    .Call(`_interprocess_rcpp_mq_get_num_msg`, name)
}

rcpp_mq_remove <- function(name) {
    .Call(`_interprocess_rcpp_mq_remove`, name)
}

rcpp_mutex_create_only <- function(name) {
    invisible(.Call(`_interprocess_rcpp_mutex_create_only`, name))
}

rcpp_mutex_open_only <- function(name) {
    invisible(.Call(`_interprocess_rcpp_mutex_open_only`, name))
}

rcpp_mutex_open_create <- function(name) {
    invisible(.Call(`_interprocess_rcpp_mutex_open_create`, name))
}

rcpp_mutex_remove <- function(name) {
    .Call(`_interprocess_rcpp_mutex_remove`, name)
}

rcpp_mutex_lock <- function(name) {
    .Call(`_interprocess_rcpp_mutex_lock`, name)
}

rcpp_mutex_try_lock <- function(name) {
    .Call(`_interprocess_rcpp_mutex_try_lock`, name)
}

rcpp_mutex_timed_lock <- function(name, timeout_ms) {
    .Call(`_interprocess_rcpp_mutex_timed_lock`, name, timeout_ms)
}

rcpp_mutex_unlock <- function(name) {
    .Call(`_interprocess_rcpp_mutex_unlock`, name)
}

rcpp_mutex_lock_sharable <- function(name) {
    .Call(`_interprocess_rcpp_mutex_lock_sharable`, name)
}

rcpp_mutex_try_lock_sharable <- function(name) {
    .Call(`_interprocess_rcpp_mutex_try_lock_sharable`, name)
}

rcpp_mutex_timed_lock_sharable <- function(name, timeout_ms) {
    .Call(`_interprocess_rcpp_mutex_timed_lock_sharable`, name, timeout_ms)
}

rcpp_mutex_unlock_sharable <- function(name) {
    .Call(`_interprocess_rcpp_mutex_unlock_sharable`, name)
}

rcpp_sem_create_only <- function(name, initial_count) {
    invisible(.Call(`_interprocess_rcpp_sem_create_only`, name, initial_count))
}

rcpp_sem_open_only <- function(name) {
    invisible(.Call(`_interprocess_rcpp_sem_open_only`, name))
}

rcpp_sem_open_create <- function(name, initial_count) {
    invisible(.Call(`_interprocess_rcpp_sem_open_create`, name, initial_count))
}

rcpp_sem_remove <- function(name) {
    .Call(`_interprocess_rcpp_sem_remove`, name)
}

rcpp_sem_post <- function(name) {
    .Call(`_interprocess_rcpp_sem_post`, name)
}

rcpp_sem_wait <- function(name) {
    .Call(`_interprocess_rcpp_sem_wait`, name)
}

rcpp_sem_try_wait <- function(name) {
    .Call(`_interprocess_rcpp_sem_try_wait`, name)
}

rcpp_sem_timed_wait <- function(name, timeout_ms) {
    .Call(`_interprocess_rcpp_sem_timed_wait`, name, timeout_ms)
}

rcpp_base62 <- function(value, hundredth, bytes) {
    .Call(`_interprocess_rcpp_base62`, value, hundredth, bytes)
}

rcpp_hash <- function(str) {
    .Call(`_interprocess_rcpp_hash`, str)
}

